name: Build

on:
  push:
    branches: 
    - main
    - release/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Docker Build
      uses: docker/setup-buildx-action@v3
    - name: Build
      uses: ./action
      with:
        file: ./Dockerfile
        





